#!/bin/zsh
# Build number for CFBundleVersion: BUILD_NUMBER override, otherwise the commit count.
# Rebuilding an uncommitted tree does not increase the commit count; choose a new override
# for a subsequent upload, using the same value for tvOS and iOS.
#   scripts/build-number.sh          prints it
#   scripts/build-number.sh --write  also rewrites Configs/Version.xcconfig (run before `xcodegen generate`)
set -euo pipefail
cd "$(dirname "$0")/.."
n="${BUILD_NUMBER:-$(git rev-list --count HEAD)}"
if [[ "$n" != <-> || "$n" == 0 ]]; then
  echo "BUILD_NUMBER must be a positive integer" >&2
  exit 2
fi
if [[ "${1:-}" == "--write" ]]; then
  cat > Configs/Version.xcconfig <<XC
// Generated by scripts/build-number.sh from the git commit count. Do not edit by hand.
CURRENT_PROJECT_VERSION = $n
XC
fi
echo "$n"
