// Generated by scripts/embed-pages.py from design/app-store/metadata/. Do not edit by hand.
//
// The App Store listing's support and privacy URLs. Served by the follow server because it is
// the one thing already answering on follow.example.com.

enum PublicPages {
    static let privacy = ####"""
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Chess TV privacy policy</title>
<meta name="description" content="What Chess TV stores, what it does not, and how to remove it.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,500;0,6..72,600;1,6..72,400&display=swap" rel="stylesheet">
<style>
  :root {
    --ground: #161916;
    --ink: #ded7c5;
    --accent: #c4d49c;
    --muted: #a9ad9c;
    --line: #2c322b;
    color-scheme: dark;
  }
  html { background: var(--ground); }
  body {
    margin: 0;
    padding: calc(2.5rem + env(safe-area-inset-top, 0px)) 1.25rem calc(4rem + env(safe-area-inset-bottom, 0px));
    background: var(--ground);
    color: var(--ink);
    font-family: "Newsreader", "Iowan Old Style", "Palatino Linotype", Palatino, Georgia, "Times New Roman", serif;
    font-size: 1.125rem;
    line-height: 1.55;
    font-optical-sizing: auto;
  }
  main { max-width: 38rem; margin: 0 auto; }
  h1 { font-weight: 500; font-size: 2.25rem; line-height: 1.15; letter-spacing: -0.01em; margin: 0 0 0.25rem; }
  h2 { font-weight: 500; font-size: 1.35rem; margin: 2.25rem 0 0.5rem; color: var(--accent); }
  p, li { margin: 0 0 1rem; }
  ul { padding-left: 1.25rem; }
  li { margin-bottom: 0.5rem; }
  a { color: var(--accent); text-decoration-thickness: 1px; text-underline-offset: 0.15em; }
  .meta { color: var(--muted); font-style: italic; margin-bottom: 2rem; }
  .plain { border-top: 1px solid var(--line); margin-top: 3rem; padding-top: 1.25rem; color: var(--muted); font-size: 1rem; }
  table { border-collapse: collapse; width: 100%; margin: 0 0 1.25rem; font-size: 1rem; }
  th, td { text-align: left; vertical-align: top; padding: 0.5rem 0.6rem 0.5rem 0; border-bottom: 1px solid var(--line); }
  th { font-weight: 500; color: var(--accent); }
  @media (max-width: 480px) { body { font-size: 1.05rem; } h1 { font-size: 1.9rem; } }
</style>
</head>
<body>
<main>
  <h1>Chess TV privacy policy</h1>
  <p class="meta">Last updated 22 September 2026 · applies to Chess TV for Apple TV, iPhone, iPad and Apple Watch</p>

  <p>Chess TV is a free viewer for live chess. It has no accounts, no advertising and no analytics. This page says exactly what leaves your device, why, and how to remove it.</p>

  <h2>On Apple TV, your settings stay local</h2>
  <p>The Apple TV app fetches games and portraits from Lichess, may fetch tournament location images from Wikipedia, and connects to Apple Music if you choose to play music. It never contacts a server of ours. Your settings stay in the app on the TV.</p>

  <h2>On iPhone, iPad and Apple Watch, notifications need a small record</h2>
  <p>If you turn on notifications and follow a player, a game or a tournament, the app registers with our notification server at <a href="https://follow.example.com">follow.example.com</a> so that the server can watch the games for you and send a push when something happens. That record is all we keep:</p>
  <table>
    <tr><th>What</th><th>Why</th></tr>
    <tr><td>Your device's push token, issued by Apple, and a random install token the server gives your device</td><td>So a notification can be delivered to your device and to no one else's</td></tr>
    <tr><td>The players, games and tournaments you follow, and which alerts you switched on for each</td><td>So the server knows what to watch and when to write to you</td></tr>
    <tr><td>Your notification preferences: mute, quiet hours and your time zone name</td><td>So the server stays quiet at night without waking your phone</td></tr>
    <tr><td>The kind of device and the app version</td><td>So an old app can be told to update if the server changes</td></tr>
    <tr><td>A delivery log of recent alerts</td><td>So the app can show you how many alerts arrived, and so we can fix duplicates</td></tr>
  </table>
  <p>We do not know who you are. There is no name, email address or Apple ID in that record. We can tell your device apart from other devices, which is what a notification needs, and nothing more.</p>

  <h2>What we do not do</h2>
  <ul>
    <li>We do not collect analytics, crash reports or usage statistics through any third-party service. There is no such code in the app.</li>
    <li>We do not sell your data or share it for advertising. Apple delivers notifications, and our hosting and network providers process requests to operate the service.</li>
    <li>We do not track you across apps or websites, and the app never asks for tracking permission.</li>
    <li>We do not store IP addresses in the notification database. Infrastructure providers may process IP addresses and operational logs to deliver and protect the service.</li>
  </ul>

  <h2>Big-swing alerts</h2>
  <p>If you switch on Big swings for a follow, our server runs the Stockfish chess engine on the public tournament positions of the games you follow, to tell you when a move changes the game. It analyses those public positions and nothing else; no information from your device is involved beyond the follow itself.</p>

  <h2>Other services the app talks to directly</h2>
  <p>Games, tournaments, arena standings, tour banners and FIDE player portraits come from <a href="https://lichess.org">lichess.org</a>, and the picture of a tournament's host city may come from <a href="https://en.wikipedia.org">Wikipedia</a>. Your device fetches these itself, as a browser would, and each request identifies the app by name and gives our contact address, as Lichess asks. Those services see the request and your IP address under their own privacy policies; nothing about it passes through us. Chess TV is not affiliated with Lichess, FIDE or the Wikimedia Foundation.</p>

  <h2>Removing your record</h2>
  <p>Remove follows in the Following tab to stop watching those players, games or tournaments. Turning notifications off in iOS Settings prevents alerts; it does not delete the server record. Deleting the app does not notify our server directly, but the record is removed automatically: once Apple reports the push token as no longer valid, the record is deleted a week later, and a record that has neither contacted the server nor received an alert for thirty days is deleted too. Reset push notifications deletes the previous registration and creates a new one with your follows restored. To have a record removed sooner, email us the approximate date you installed the app and the players or tournaments you follow, and we will find and delete it.</p>

  <h2>Retention</h2>
  <p>Delivery records are deleted after seven days. A registration whose push token Apple has rejected is deleted after seven days, and one that has not contacted the server or received an alert in thirty days is deleted then. Deleting a registration also deletes its follows, preferences, Live Activity tokens and delivery records.</p>
  <p>The server keeps a copy of its database from each of its last seven software updates, so a deleted record can survive in those copies until they are replaced, normally within a few weeks. Server logs name a random device number, never a push token, and are overwritten after about 30 MB of activity.</p>

  <h2>Children</h2>
  <p>The app does not ask for a name, age or contact details. Device identifiers and notification preferences described above may still be processed when notifications are enabled.</p>

  <h2>Changes and contact</h2>
  <p>If this policy changes, the date at the top changes with it, and Settings links here. Questions go to <a href="mailto:zzzlabshq@gmail.com">zzzlabshq@gmail.com</a>. Chess TV includes GPLv3-licensed Stockfish. Its licence texts and attributions can be read in Settings → Credits, and the app's source code is at <a href="https://github.com/og-nav/Chess-TV">github.com/og-nav/Chess-TV</a>.</p>

  <p class="plain">Chess TV is made by one person as a service to chess fans. It is not a company, it does not make money, and it has no reason to want your data.</p>
</main>
</body>
</html>
"""####

    static let support = ####"""
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>Chess TV support</title>
<meta name="description" content="Help with Chess TV for Apple TV, iPhone, iPad and Apple Watch.">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Newsreader:ital,opsz,wght@0,6..72,400;0,6..72,500;0,6..72,600;1,6..72,400&display=swap" rel="stylesheet">
<style>
  :root {
    --ground: #161916;
    --ink: #ded7c5;
    --accent: #c4d49c;
    --muted: #a9ad9c;
    --line: #2c322b;
    color-scheme: dark;
  }
  html { background: var(--ground); }
  body {
    margin: 0;
    padding: calc(2.5rem + env(safe-area-inset-top, 0px)) 1.25rem calc(4rem + env(safe-area-inset-bottom, 0px));
    background: var(--ground);
    color: var(--ink);
    font-family: "Newsreader", "Iowan Old Style", "Palatino Linotype", Palatino, Georgia, "Times New Roman", serif;
    font-size: 1.125rem;
    line-height: 1.55;
    font-optical-sizing: auto;
  }
  main { max-width: 38rem; margin: 0 auto; }
  h1 { font-weight: 500; font-size: 2.25rem; line-height: 1.15; letter-spacing: -0.01em; margin: 0 0 0.25rem; }
  h2 { font-weight: 500; font-size: 1.35rem; margin: 2.25rem 0 0.5rem; color: var(--accent); }
  p, li { margin: 0 0 1rem; }
  ul { padding-left: 1.25rem; }
  li { margin-bottom: 0.5rem; }
  a { color: var(--accent); text-decoration-thickness: 1px; text-underline-offset: 0.15em; }
  .meta { color: var(--muted); font-style: italic; margin-bottom: 2rem; }
  .plain { border-top: 1px solid var(--line); margin-top: 3rem; padding-top: 1.25rem; color: var(--muted); font-size: 1rem; }
  table { border-collapse: collapse; width: 100%; margin: 0 0 1.25rem; font-size: 1rem; }
  th, td { text-align: left; vertical-align: top; padding: 0.5rem 0.6rem 0.5rem 0; border-bottom: 1px solid var(--line); }
  th { font-weight: 500; color: var(--accent); }
  @media (max-width: 480px) { body { font-size: 1.05rem; } h1 { font-size: 1.9rem; } }
</style>
</head>
<body>
<main>
<h1>Chess TV support</h1>
<p class="meta">Live chess on Apple TV, iPhone, iPad and Apple Watch</p>
<p>For help, bug reports or image attribution and removal requests, email <a href="mailto:zzzlabshq@gmail.com">zzzlabshq@gmail.com</a>. Include your device model, OS version, app version and what happened. Please do not send push tokens or other credentials.</p>
<h2>Start watching</h2>
<p>Choose a Lichess TV channel, an arena or a tournament from the home screen. For tournaments, choose a round and then a board. Coverage and timing depend on the Lichess relay.</p>
<h2>Alerts stopped arriving</h2>
<p>On iPhone or iPad, open Settings → Notifications in Chess TV. Check permission, mute and quiet hours, then try Reset push notifications. This repairs registration and restores your follows. If iOS has disabled notifications, enable them in iOS Settings first. Push delivery can be delayed by the system and needs a physical device.</p>
<h2>Apple Watch</h2>
<p>Open Chess TV on the paired iPhone to sync your follows. A saved board may remain visible while the Watch is disconnected. Open the Watch app in the foreground to refresh it.</p>
<h2>Apple Music on TV</h2>
<p>Connect Apple Music from Settings on Apple TV. Playback requires an eligible Apple Music subscription and authorization. Chess viewing does not require Music access.</p>
<h2>Data and credits</h2>
<p>Read the <a href="/privacy">privacy policy</a> for notification data and retention. Settings → Credits contains Lichess, FIDE, Stockfish and artwork attributions and the bundled licence texts. Chess TV is not affiliated with Lichess or FIDE.</p>
</main>
</body>
</html>
"""####
}
